name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

env:
  CLUSTER_NAME: gh-action-cluster
  TASK_DEFINITION: sample-fargate
  SERVICE_NAME: fargate-service

jobs:
  deploy_to_fargate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Fargate
      run: |
        # Register a new task definition
        TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://$GITHUB_WORKSPACE/task-def.json | jq -r '.taskDefinition.taskDefinitionArn')

        # Update the service to use the new task definition
        aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $TASK_DEF_ARN 
